### ISSUE TITLE
track sessions

### ISSUE THREAD

**Issue by GeorgLink** [Bugmark-Simulator/bugmark_simulation#87]
- [x] START SIMULATION SESSION
  - [x] assign session UID
  - [x] track user's session's starting balances [reset to 1000 each session]
  - [x] track who participates during session #107
- [x] END SIMULATION SESSION
  - [x] simulate days until last contract expires, ideally in short time [decided against this] #95 
  - [x] simulate market place (for final earnings - session earnings),  [decided against this] #95 
  - [x] simulate work queues (for fairness),  [decided against this] #95 
  - [x] simulate funder behavior (for graphs) [decided against this] #95

**Comment by GeorgLink** [comment]
tracking user balances (earnings) within each session:

- jfields:
  - sessions
    - 1
      - id
      - datetime 
      - end_balance
    - 2
      - ...
